name: TotalFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.5
description: Plugin for the Total Freedom server
author: StevenLawson / Madgeek1450
commands:
  cake:
    description: For the people that are still alive.
    usage: /<command>
  creative:
    description: Quickly change your own gamemode to creative, or define someone's username to change theirs.
    usage: /<command> [partialname]
  deopall:
    description: Superadmin command - Deop everyone on the server.
    usage: /<command>
  explosives:
    description: Superadmin command - Enable/disable explosives and set effect radius.
    usage: /<command> <on|off> [radius]
  fireplace:
    description: Superadmin command - Enable/disable fire placement.
    usage: /<command> <on|off>
  firespread:
    description: Superadmin command - Enable/disable fire spread.
    usage: /<command> <on|off>
  flatlands:
    description: Goto the flatlands.
    usage: /<command>
  fr:
    description: Superadmin command - Freeze all players (toggles on and off).
    usage: /<command>
  gadmin:
    description: Superadmin command - Use admin commands on someone by hash. Use mode 'list' to get a player's hash. Other modes are kick, nameban, ipban, ban, op, deop, ci
    usage: /<command> [list | <kick|nameban|ipban|ban|op|deop|ci> <targethash>]
  gtfo:
    description: Superadmin command - Makes someone GTFO (deop and ip ban by username).
    usage: /<command> [partialname]
  lavadmg:
    description: Superadmin command - Enable/disable lava damage.
    usage: /<command> <on|off>
  lavaplace:
    description: Superadmin command - Enable/disable lava placement.
    usage: /<command> <on|off>
  list:
    description: Lists the real names of all online players.
    usage: /<command>
  listreal:
    description: Lists the real names of all online players.
    usage: /<command>
  mp:
    description: Use moblimiter to purge all mobs.
    usage: /<command>
  nonuke:
    description: Attempt to detect "invisible griefers" and "nukers".
    usage: /<command> <on|off> [range] [blockrate]
  opall:
    description: Superadmin command - Op everyone on the server, optionally change everyone's gamemode at the same time.
    usage: /<command> [-c|-s]
  opme:
    description: Superadmin command - Automatically ops user.
    usage: /<command>
  prelog:
    description: Superadmin command - Enable/disable the command prelogger. When this is on, logs will be filled with many duplicate messages.
    usage: /<command> <on|off>
  qdeop:
    description: Quick De-Op - deop someone based on a partial name.
    usage: /<command> <partialname>
  qop:
    description: Quick Op - op someone based on a partial name.
    usage: /<command> <partialname>
  radar:
    description: Shows nearby people sorted by distance.
    usage: /<command>
  rd:
    description: Use WorldEdit to remove drops, arrows, and primed TNT.
    usage: /<command>
  say:
    description: Broadcasts the given message as the console, includes sender.
    usage: /<command> <message>
  skylands:
    description: Goto the skylands.
    usage: /<command>
  status:
    description: Show random server info.
    usage: /<command>
  stop:
    description: Superadmin command - Kicks everyone and stops the server.
    usage: /<command>
  survival:
    description: Quickly change your own gamemode to survival, or define someone's username to change theirs.
    usage: /<command> [partialname]
  waterplace:
    description: Superadmin command - Enable/disable water placement.
    usage: /<command> <on|off>
  wildcard:
    description: Superadmin command - Run any command on all users, username placeholder = ?.
    usage: /<command> [fluff] ? [fluff] ?