name: TotalFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.0.2
description: Plugin for the Total Freedom server
author: StevenLawson / Madgeek1450
commands:
  deopall:
    description: Superadmin command - Deop everyone on the server.
    usage: /<command>
  listreal:
    description: Lists the real names of all online players.
    usage: /<command>
  opall:
    description: Superadmin command - Op everyone on the server.
    usage: /<command>
  opme:
    description: Superadmin command - Automatically ops user.
    usage: /<command>
  qdeop:
    description: Quick De-Op - deop someone based on a partial name.
    usage: /<command> [partialname]
  qop:
    description: Quick Op - op someone based on a partial name.
    usage: /<command> [partialname]
