name: TotalFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 1.4
description: Plugin for the Total Freedom server
author: StevenLawson / Madgeek1450
commands:
  creative:
    description: Quickly change your own gamemode to creative, or define someone's username to change theirs.
    usage: /<command> [partialname]
  deopall:
    description: Superadmin command - Deop everyone on the server.
    usage: /<command>
  explosives:
    description: Superadmin command - Enable/disable explosives and set effect radius.
    usage: /<command> <on|off> [radius]
  fire:
    description: Superadmin command - Enable/disable fire.
    usage: /<command> <on|off>
  gtfo:
    description: Superadmin command - Makes someone GTFO (deop and ip ban by username).
    usage: /<command> [partialname]
  lavadmg:
    description: Superadmin command - Enable/disable lava damage.
    usage: /<command> <on|off>
  list:
    description: Lists the real names of all online players.
    usage: /<command>
  listreal:
    description: Lists the real names of all online players.
    usage: /<command>
  mp:
    description: Use moblimiter to purge all mobs.
    usage: /<command>
  opall:
    description: Superadmin command - Op everyone on the server, optionally change everyone's gamemode at the same time.
    usage: /<command> [-c|-s]
  opme:
    description: Superadmin command - Automatically ops user.
    usage: /<command>
  prelog:
    description: Superadmin command - Enable/disable the command prelogger. When this is on, logs will be filled with many duplicate messages.
    usage: /<command> <on|off>
  qdeop:
    description: Quick De-Op - deop someone based on a partial name.
    usage: /<command> <partialname>
  qop:
    description: Quick Op - op someone based on a partial name.
    usage: /<command> <partialname>
  radar:
    description: Shows nearby people sorted by distance.
    usage: /<command>
  rd:
    description: Use WorldEdit to remove drops, arrows, and primed TNT.
    usage: /<command>
  say:
    description: Broadcasts the given message as the console, includes sender.
    usage: /<command> <message>
  stop:
    description: Kicks everyone and stops the server.
    usage: /<command>
  survival:
    description: Quickly change your own gamemode to survival, or define someone's username to change theirs.
    usage: /<command> [partialname]
  wildcard:
    description: Superadmin command - Run any command on all users, username placeholder = ?.
    usage: /<command> [fluff] ? [fluff] ?